**3.** El Teorema Fundamental de la Aritmética menciona que todo número se puede descomponer de forma única como producto de factores primos. Por ejemplo $60 = 2^2*3^1*5^1$. Codifique una función **factoriza(n)** que reciba un entero positivo $n$ y cuyo output sea un array donde la primera fila contiene los numeros primosde la factorización en orden ascendente y la segunda fila contiene las potencias correspondientes. Por ejemplo **factoriza(60)** el output será el **numpy array[[2,3,5],[2,1,1]]**.

Adicionalmente cree una función llamada **test(?,?,..?)** (como usted desee) que le ayude a verificar los calculos que hizo la función factoriza.

In [2]:
import numpy as np
from collections import Counter

def isPrime(n):
    '''
        input: n ->  Entero positivo
        output: True or False
        
    '''
    band =  0
    for i in range(2,n):
        if(n%i==0):
            band+=1
    if(n == 1):
        return False
    elif(band>0):
        return False
    else:
        return True

    
def factoriza(n): 
    '''
        input: n ->  Entero positivo
        output: np.array[[],[]]
        
    '''
    primes = []

    for i in range(1,n+1):
        if(n%i == 0):
            if(isPrime(i)):
                primes.append(i)

    vals = []
    vals2 = []
    coef = []

    while(n!=1):
        for p in primes:
            if(n%p==0):
                vals.append(p)
                   
                n/=p

    vals.sort()
    for k,v in Counter(vals).items():
        coef.append(v)
        vals2.append(k)

    return np.array([vals2,coef])

In [3]:
factoriza(60)

array([[2, 3, 5],
       [2, 1, 1]])

In [4]:
factoriza(10)

array([[2, 5],
       [1, 1]])

In [5]:
factoriza(100)

array([[2, 5],
       [2, 2]])

In [6]:
factoriza(500)

array([[2, 5],
       [2, 3]])

In [7]:
factoriza(999)

array([[ 3, 37],
       [ 3,  1]])

In [8]:
factoriza(551)

array([[19, 29],
       [ 1,  1]])

In [88]:
import unittest

def test(n,expectedValue):

    np.testing.assert_array_equal(factoriza(n),expectedValue,err_msg='-> El test falló', verbose=False)
    
    unittest.main(argv=[''], verbosity=0, exit=False)

In [89]:
test(60,np.array([[2, 3, 5],[2, 1, 1]]))

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK


In [91]:
test(50,np.array([[2, 5],[1, 2]]))

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK


In [93]:
test(24,np.array([[2, 3],[3, 1]]))

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK


In [97]:
test(25,np.array([[5],[2]]))

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
