**3.** El Teorema Fundamental de la Aritmética menciona que todo número se puede descomponer de forma única como producto de factores primos. Por ejemplo $60 = 2^2*3^1*5^1$. Codifique una función **factoriza(n)** que reciba un entero positivo $n$ y cuyo output sea un array donde la primera fila contiene los numeros primosde la factorización en orden ascendente y la segunda fila contiene las potencias correspondientes. Por ejemplo **factoriza(60)** el output será el **numpy array[[2,3,5],[2,1,1]]**.

In [167]:
import numpy as np
from collections import Counter

def isPrime(n):
    '''
        input: n ->  Entero positivo
        output: True or False
        
    '''
    band =  0
    for i in range(2,n):
        if(n%i==0):
            band+=1
    if(n == 1):
        return False
    elif(band>0):
        return False
    else:
        return True

    
def factoriza(n): 
    '''
        input: n ->  Entero positivo
        output: np.array[[],[]]
        
    '''
    primes = []

    for i in range(1,n+1):
        if(n%i == 0):
            if(isPrime(i)):
                primes.append(i)

    vals = []
    vals2 = []
    coef = []

    while(n!=1):
        for p in primes:
            if(n%p==0):
                vals.append(p)
                   
                n/=p

    vals.sort()
    for k,v in Counter(vals).items():
        coef.append(v)
        vals2.append(k)

    return np.array([vals2,coef])

In [168]:
factoriza(60)

array([[2, 3, 5],
       [2, 1, 1]])

In [169]:
factoriza(10)

array([[2, 5],
       [1, 1]])

In [170]:
factoriza(100)

array([[2, 5],
       [2, 2]])

In [171]:
factoriza(500)

array([[2, 5],
       [2, 3]])

In [172]:
factoriza(999)

array([[ 3, 37],
       [ 3,  1]])

In [173]:
factoriza(551)

array([[19, 29],
       [ 1,  1]])